---
configuration_application:
  apex_ip: 10.0.0.5 # dummy value
  astra_ip: 10.0.0.6 # dummy value
  meson_ip: 10.0.0.7 # dummy value
  ingress_intranet_agw_ip: 10.210.118.202 # dummy value
  ingress_internet_agw_ip: 100.73.38.74 # dummy value   
  ingress_internet_aks_ip: 100.2.0.95 # dummy value
  ingress_intranet_aks_ip: 100.2.0.95 # dummy value
  ingress_internet_aks_fqdn: aks.internet.caflabs.com # dummy value  
  ingress_intranet_aks_fqdn: aks.intranet.caflabs.com # dummy value    
  ingress_internet_agw_fqdn: demoapp1.internet.caflabs.com # dummy value  
  ingress_intranet_agw_fqdn: demoapp1.intranet.caflabs.com # dummy value    
  egress_intranet_firewall_ip: 100.73.39.4 # dummy value intranet firewall subnet cidr + 4     
  egress_internet_firewall_ip: 10.210.119.4 # dummy value internet firewall subnet cidr + 4    
  # ingress_intranet_domain: caflabs.com # dummy value     
  # ingress_internet_domain: caflabs.com # dummy value     
 



                   
               
           
