---
# id = "/subscriptions/e22a351f-db36-4a02-9793-0f2189d5f3ab/resourceGroups/ignite-rg-dev-env-re1/providers/Microsoft.Network/virtualNetworks/ignite-vnet-spoke-re1"
configuration_application:
  apex_ip: 10.0.0.5
  astra_ip: 10.0.0.6
  meson_ip: 10.0.0.7
  ingress_intranet_agw_ip: 10.2.0.74
  ingress_internet_agw_ip: 100.2.0.74
  ingress_internet_aks_ip: 100.2.0.95
  ingress_intranet_aks_ip: 100.2.0.95
  # aks_ip_internet: 100.2.0.94
  # aks_ip_intranet: 100.2.0.94
  # agw_ip_internet: 100.1.0.74
  # agw_ip_intranet: 10.1.0.74  



                   
               
           
