---
configuration_application:
  on_prem_api_ip: 10.0.0.5 # dummy value
  on_prem_sftp_ip: 10.0.0.6 # dummy value
  on_prem_mq_ip: 10.0.0.7 # dummy value
  ingress_intranet_agw_ip: 10.2.0.74
  ingress_internet_agw_ip: 100.2.0.74
  ingress_internet_aks_ip: 100.2.0.95
  ingress_intranet_aks_ip: 100.2.0.95
  ingress_internet_aks_fqdn: aks.internet.caflabs.com # dummy value  
  ingress_intranet_aks_fqdn: aks.intranet.caflabs.com # dummy value    
  ingress_internet_agw_fqdn: demoapp1.internet.caflabs.com # dummy value  
  ingress_intranet_agw_fqdn: demoapp1.intranet.caflabs.com # dummy value    
  egress_intranet_firewall_ip: 10.2.0.4 # dummy value intranet firewall subnet cidr + 4     
  egress_internet_firewall_ip: 100.2.0.4 # dummy value internet firewall subnet cidr + 4    
  # ingress_intranet_domain: caflabs.com # dummy value     
  # ingress_internet_domain: caflabs.com # dummy value    

               
           
